{"title": "Hermosa casa con amplio patio. Zona muy tranquila", "link": "http://www.escobarnegociosinmobiliarios.com/propiedad/alquiler-de-casa-en-san-carlos-de-bariloche-bariloche-rio-negro-2663-181015", "price": "ARS 30000"}
{"title": "Monoambiente luminoso", "link": "http://www.escobarnegociosinmobiliarios.com/propiedad/alquiler-de-departamento-en-san-carlos-de-bariloche-bariloche-rio-negro-2663-221942", "price": "ARS 25000"}
{"title": "Monoambiente  impecable", "link": "http://www.escobarnegociosinmobiliarios.com/propiedad/alquiler-de-departamento-en-san-carlos-de-bariloche-bariloche-rio-negro-2663-217689", "price": "ARS 33000"}
{"title": "Importante Propiedad Hostel/oficinas/aulas + Local Comercial", "link": "http://www.escobarnegociosinmobiliarios.com/propiedad/alquiler-de-casa-en-centro-bariloche-rio-negro-2663-213571", "price": "ARS 150000"}
{"title": "Oficina amplia en Galeria Via Firenze.", "link": "http://www.escobarnegociosinmobiliarios.com/propiedad/alquiler-de-oficina-en-san-carlos-de-bariloche-bariloche-rio-negro-2663-180080", "price": "ARS 18000"}
{"title": "Departamento 2 dormitorios semi c\u00e9ntrico", "link": "http://www.escobarnegociosinmobiliarios.com/propiedad/alquiler-de-departamento-en-san-carlos-de-bariloche-bariloche-rio-negro-2663-204430", "price": "ARS 28000"}
{"title": "Impecable departamento", "link": "http://www.escobarnegociosinmobiliarios.com/propiedad/alquiler-de-departamento-en-centro-bariloche-rio-negro-2663-199435", "price": "ARS 17000"}
{"title": "Casa en barrio muy tranquilo 2 dormitorios", "link": "http://www.escobarnegociosinmobiliarios.com/propiedad/alquiler-de-casa-en-covivar-bariloche-rio-negro-2663-198095", "price": "ARS 22000"}
{"title": "Propiedad para amantes de la naturaleza y de la tranquilidad, frente al Lago Gutierrez. con excelente vista.", "link": "http://www.escobarnegociosinmobiliarios.com/propiedad/alquiler-de-casa-en-san-carlos-de-bariloche-bariloche-rio-negro-2663-161588", "price": "ARS 70000"}
{"title": "PH a metros del lago", "link": "http://www.escobarnegociosinmobiliarios.com/propiedad/alquiler-de-ph-en-dina-huapi-pilcaniyeu-rio-negro-2663-175247", "price": "ARS 16500"}
{"title": "Casa con amplio lote", "link": "http://www.escobarnegociosinmobiliarios.com/propiedad/alquiler-de-casa-en-san-carlos-de-bariloche-bariloche-rio-negro-2663-193396", "price": "ARS 29000"}
{"title": "Depto 3 dormitorios S/Elordi", "link": "http://www.escobarnegociosinmobiliarios.com/propiedad/alquiler-de-departamento-en-san-carlos-de-bariloche-bariloche-rio-negro-2663-193457", "price": "ARS 26000"}
{"title": "Monoambientes Dina Huapi", "link": "http://www.escobarnegociosinmobiliarios.com/propiedad/alquiler-de-departamento-en-san-carlos-de-bariloche-bariloche-rio-negro-2663-193454", "price": "ARS 18000"}
{"title": "Local Comercial en Shopping Patagonia", "link": "http://www.escobarnegociosinmobiliarios.com/propiedad/alquiler-de-local-comercial-en-san-carlos-de-bariloche-bariloche-rio-negro-2663-163011", "price": "ARS 22100"}
{"title": "Local Comercial Shopping Patagonia", "link": "http://www.escobarnegociosinmobiliarios.com/propiedad/alquiler-de-local-comercial-en-san-carlos-de-bariloche-bariloche-rio-negro-2663-163012", "price": "ARS 33000"}
{"title": "Local Comercial Gastronomico en &quotShopping Patagonia&quot", "link": "http://www.escobarnegociosinmobiliarios.com/propiedad/alquiler-de-local-comercial-en-san-carlos-de-bariloche-bariloche-rio-negro-2663-163014", "price": "ARS 41000"}
{"title": "Local Comercial en &quotShopping Patagonia&quot", "link": "http://www.escobarnegociosinmobiliarios.com/propiedad/alquiler-de-local-comercial-en-san-carlos-de-bariloche-bariloche-rio-negro-2663-163013", "price": "ARS 34800"}
{"title": "Lotes en la entrada del frutillar", "link": "http://www.escobarnegociosinmobiliarios.com/propiedad/alquiler-de-terreno-en-san-carlos-de-bariloche-bariloche-rio-negro-2663-156808", "price": "ARS 20000"}
{"title": "Alquiler! Hermoso departamento frente al Lago Nahuel Huapi!", "link": "https://www.ferrarapropiedades.com/properties/alquiler-hermoso-departamento-frente-al-lago-nahuel-huapi/", "price": 85000}
{"title": "Galpon en venta y alquiler Centro ", "link": "https://loscerrospropiedades.com/galpon-en-venta-y-alquiler-en-centro-ficha-lcr402", "price": "130000"}
{"title": "Galpon en alquiler Centro ", "link": "https://loscerrospropiedades.com/galpon-en-alquiler-en-centro-ficha-lcr758", "price": "210000"}
{"title": "Local en alquiler Centro ", "link": "https://loscerrospropiedades.com/local-en-alquiler-en-centro-ficha-lcr572", "price": "130000"}
{"title": "Local en alquiler Centro ", "link": "https://loscerrospropiedades.com/local-en-alquiler-en-centro-ficha-lcr503", "price": "55000"}
{"title": "Trato Directo alquila semipermanente caba\u00f1a en Lago Puelo desde diciembre a marzo", "link": "https://www.tratodirecto.com.ar/propiedad/properties/alquiler-de-cabana-lago-puelo", "price": "$AR 160.000"}
{"title": "ALQUILER PERMANENTE EN DINA HUAPI \u00a0Trato Directo alquila CASA con Costa de Lago con 30 metros lineales, a partir de febrero de 2022", "link": "https://www.tratodirecto.com.ar/propiedad/properties/alquiler-de-casa-permanente-dina-huapi", "price": "U$S 1.000"}
{"title": "", "link": "https://www.tratodirecto.com.ar/propiedad/properties/local-comercial-a-estrenar", "price": "$AR 50.000"}
{"title": "Casa Dos dormitorios, con patio", "link": "https://www.tratodirecto.com.ar/propiedad/properties/casa645vv", "price": "$AR 28000+gastos"}
